spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shop?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 240518.a

mybatis-plus:
  configuration:
    #开启下划线转驼峰
    map-underscore-to-camel-case: true

paicoding:
  sensitive: # 敏感词校验相关配置
    enable: true
    deny: # 自定义的敏感词，英文逗号分割
    allow: # 自定义的非敏感词，英文逗号分割
